config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show

    end

    def index
        @articles = Article.all 
    end

    def new
        @article = Article.new
    end

    def create 
        @article = Article.new(params.require(:article).permit(:title, :description))
        if @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article
        else
            render "new", status: :unprocessable_entity
        end
    end

    def edit

    end

    def update
        if @article.update(params.require(:article).permit(:title, :description)) 
            flash[:notice] = "Article was update successfully"
            redirect_to @article
        else
            render "edit"
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

end  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<% if @article.errors.any? %>
    <h2>The following errors prevented the article from being saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
           <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

    <p>
        <strong>
            <%= f.label :title %><br>
        </strong>
        <%= f.text_field :title %>

    </p>

    <p>
        <strong>
            <%= f.label :description %><br>
        </strong>
        <%= f.text_area :description %>

    </p>

    <p>
        <strong>
            <%= f.submit %>
        </strong>
    </p>

    
<% end %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan = "3">Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <td><%= link_to "Show", article_path(article) %></td>
                <td><%= link_to "Delete", article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
                <td><%= link_to "Edit", edit_article_path(article)%></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br>

<%= link_to new_article_path do %>
    <button> New article </button>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<% if @article.errors.any? %>
    <h2>The following errors prevented the article from being saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
           <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>
<%= form_with scope: @article, url: articles_path, local: true do |f| %>

    <p>
        <strong>
            <%= f.label :title %><br>
        </strong>
        <%= f.text_field :title %>

    </p>

    <p>
        <strong>
            <%= f.label :description %><br>
        </strong>
        <%= f.text_area :description %>

    </p>

    <p>
        <strong>
            <%= f.submit %>
        </strong>

        <%= link_to articles_path do %>
        <button>Return</button>
        <% end %>

    </p>

    
<% end %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><strong>Title:</strong> <%=@article.title%></p>
<p><strong>Description: </strong><%=@article.description%></p>

<%= link_to edit_article_path(@article) do %>
  <button>Edit</button>
<% end %>

<%= link_to article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
  <button>Delete</button>
<% end %>

<%= link_to articles_path do %>
  <button>Return</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to articles_path do %>
  <button>Articles Listing</button>
<% end %>

<%= link_to root_path do %>
    <button> Home </button>
<% end %>

app/views/pages/home.html.erb
<h1>Welcome to the home page</h1>

<%= link_to articles_path do %>
  <button>Articles Listing</button>
<% end %>

<%= link_to about_path do %>
    <button> About </button>
<% end %>